# Generated by Django 5.2.7 on 2026-07-05 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_announcement_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('monthly_contribution', 'Monthly Contribution'), ('loan_repayment', 'Loan Repayment'), ('welfare_contribution', 'Welfare Contribution'), ('registration_fee', 'Registration Fee'), ('penalty', 'Penalty'), ('other', 'Other')], max_length=50)),
                ('amount_expected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_reference', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('contribution_month', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
                ('related_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='core.loan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KcbPaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_reference', models.CharField(max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_mobile_number', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('channel_code', models.CharField(blank=True, max_length=50, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('credit_account_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_short_code', models.CharField(blank=True, max_length=100, null=True)),
                ('till_number', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kcb_notifications', to='payments.paymentintent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
