# Generated by Django 5.2.7 on 2025-10-27 03:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_announcement_meetingnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='welfare',
            name='status',
            field=models.CharField(choices=[('partially paid', 'Partially Paid'), ('fully paid', 'Fully Paid'), ('not paid', 'Not Paid')], default='not paid', max_length=20),
        ),
    ]
