# Generated by Django 5.2.7 on 2025-10-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loan_due_date_loan_loan_date_alter_welfare_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repayment_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid')], default='not_paid', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
