# Generated by Codex on 2025-10-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_loan_repayment_status_loan_repayment_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="welfare",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="welfare",
            name="status",
            field=models.CharField(
                choices=[
                    ("partially_paid", "Partially Paid"),
                    ("fully_paid", "Fully Paid"),
                    ("late", "Late"),
                    ("not_paid", "Not Paid"),
                ],
                default="not_paid",
                max_length=20,
            ),
        ),
    ]
