# Generated by Django 5.2.7 on 2025-10-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loan_repayment_status_loan_repayment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('fully_paid', 'Fully Paid'), ('partially_paid', 'Partially Paid'), ('late', 'Late'), ('not_paid', 'Not Yet Paid')], default='not_paid', max_length=20),
        ),
    ]
