# Generated by Django 5.2.7 on 2025-10-30 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contribution_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingnote',
            options={},
        ),
        migrations.RemoveField(
            model_name='meetingnote',
            name='body',
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='content',
            field=models.TextField(blank=True, help_text='Optional full text of minutes'),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='minutes/'),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
