# Generated by Django 5.2.7 on 2026-01-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_welfare_status_late_updated_at'),
        ('core', '0007_notification'),
    ]

    operations = [
    ]
