# Generated by Django 5.2.7 on 2026-02-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_merge_20260124_0646"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="amount_repaid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
