# Generated by Django 5.2.7 on 2026-02-01 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_loan_amount_repaid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="amount_repaid",
            new_name="total_paid_so_far",
        ),
    ]
