# Generated by Django 5.2.7 on 2026-02-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_amount_repaid_to_total_paid_so_far'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['-month', '-created_at'], 'permissions': [('export_contributions', 'Can export contributions'), ('edit_contribution_amount', 'Can edit contribution amount')]},
        ),
        migrations.AlterModelOptions(
            name='welfare',
            options={'ordering': ['-date_given'], 'permissions': [('edit_welfare_amount', 'Can edit welfare amount')]},
        ),
    ]
