# Generated by Django 5.2.7 on 2026-02-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_contribution_options_alter_welfare_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
