# Generated by Django 5.2.7 on 2026-07-05 17:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_announcement_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together={('member', 'month')},
        ),
    ]
