# Generated by Django 5.2.7 on 2026-08-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_contribution_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "letter_type",
                    models.CharField(
                        choices=[
                            ("loan_approval", "Loan approval"),
                            ("loan_demand", "Loan demand"),
                            ("membership_confirmation", "Membership confirmation"),
                            ("removal_notice", "Removal notice"),
                            ("contribution_reminder", "Contribution reminder"),
                            ("welfare_communication", "Welfare communication"),
                            ("general", "General correspondence"),
                        ],
                        max_length=40,
                    ),
                ),
                ("header_content", models.TextField(blank=True)),
                ("footer_content", models.TextField(blank=True)),
                ("body_template", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CommitteeLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=30, unique=True)),
                (
                    "letter_type",
                    models.CharField(
                        choices=[
                            ("loan_approval", "Loan approval"),
                            ("loan_demand", "Loan demand"),
                            ("membership_confirmation", "Membership confirmation"),
                            ("removal_notice", "Removal notice"),
                            ("contribution_reminder", "Contribution reminder"),
                            ("welfare_communication", "Welfare communication"),
                            ("general", "General correspondence"),
                        ],
                        default="general",
                        max_length=40,
                    ),
                ),
                ("recipient_name", models.CharField(max_length=160)),
                ("recipient_organization", models.CharField(blank=True, max_length=180)),
                ("recipient_address", models.TextField(blank=True)),
                ("subject", models.CharField(max_length=220)),
                ("body", models.TextField()),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrections",
                        to="core.committeeletter",
                    ),
                ),
                ("signatory_name", models.CharField(max_length=160)),
                ("signatory_position", models.CharField(max_length=120)),
                (
                    "supporting_attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="committee_letters/attachments/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("pdf_generated", "PDF generated"),
                            ("issued", "Issued"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="committee_letters/generated/",
                    ),
                ),
                ("verification_code", models.CharField(blank=True, max_length=30, unique=True)),
                ("date_issued", models.DateField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="committee_letters_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="committee_letters_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_committee_letter", "Can approve committee letters"),
                    ("issue_committee_letter", "Can issue committee letters"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommitteeLetterAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=80)),
                ("status_from", models.CharField(blank=True, max_length=20)),
                ("status_to", models.CharField(blank=True, max_length=20)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_entries",
                        to="core.committeeletter",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Signatory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("official_name", models.CharField(max_length=160)),
                ("position", models.CharField(max_length=120)),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="protected/signatories/signatures/",
                    ),
                ),
                (
                    "stamp_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="protected/signatories/stamps/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="letter_signatory_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "signatories",
                "ordering": ["position", "official_name"],
            },
        ),
        migrations.AddField(
            model_name="committeeletter",
            name="signatory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="letters",
                to="core.signatory",
            ),
        ),
    ]
