# Generated by Django 5.2.7 on 2026-08-03

import datetime
import re
import secrets

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


REFERENCE_RE = re.compile(r"^TH(?:P|YG)/COM/(?P<year>\d{4})/(?P<number>\d+)$")


def _date_from_datetime(value):
    if not value:
        return None
    if django.utils.timezone.is_naive(value):
        value = django.utils.timezone.make_aware(
            value,
            django.utils.timezone.get_current_timezone(),
        )
    return django.utils.timezone.localtime(value).date()


def _datetime_from_date(value):
    if not value:
        return None
    combined = datetime.datetime.combine(value, datetime.time.min)
    return django.utils.timezone.make_aware(
        combined,
        django.utils.timezone.get_current_timezone(),
    )


def _build_verification_code(reference, used_codes):
    reference_suffix = reference.replace("THYG/COM/", "THYG-").replace("/", "-")
    while True:
        code = f"{reference_suffix}-{secrets.token_hex(3).upper()}"
        if code not in used_codes:
            used_codes.add(code)
            return code


def upgrade_letters(apps, schema_editor):
    CommitteeLetter = apps.get_model("core", "CommitteeLetter")
    LetterReferenceSequence = apps.get_model("core", "LetterReferenceSequence")

    status_map = {
        "reviewed": "submitted",
        "pdf_generated": "approved",
    }

    used_codes = set(
        CommitteeLetter.objects.exclude(verification_code="").values_list(
            "verification_code",
            flat=True,
        )
    )
    max_by_year = {}
    pending_reference_ids = []

    for letter in CommitteeLetter.objects.order_by("created_at", "id"):
        if letter.date_issued:
            letter.letter_date = letter.date_issued
        elif letter.approved_at:
            letter.letter_date = _date_from_datetime(letter.approved_at)
        elif letter.created_at:
            letter.letter_date = _date_from_datetime(letter.created_at)
        elif not letter.letter_date:
            letter.letter_date = django.utils.timezone.localdate()

        old_status = letter.status
        letter.status = status_map.get(letter.status, letter.status)
        if old_status == "issued" and letter.date_issued and not letter.issued_at:
            letter.issued_at = _datetime_from_date(letter.date_issued)

        if letter.reference_number.startswith("THP/COM/"):
            letter.reference_number = letter.reference_number.replace(
                "THP/COM/",
                "THYG/COM/",
                1,
            )

        match = REFERENCE_RE.match(letter.reference_number or "")
        if match:
            year = int(match.group("year"))
            number = int(match.group("number"))
            max_by_year[year] = max(max_by_year.get(year, 0), number)
        else:
            pending_reference_ids.append(letter.pk)

        if letter.verification_code.startswith("THP-"):
            used_codes.discard(letter.verification_code)
            letter.verification_code = letter.verification_code.replace("THP-", "THYG-", 1)
            used_codes.add(letter.verification_code)
        elif not letter.verification_code:
            letter.verification_code = _build_verification_code(
                letter.reference_number,
                used_codes,
            )

        letter.save(
            update_fields=[
                "letter_date",
                "status",
                "issued_at",
                "reference_number",
                "verification_code",
            ]
        )

    for letter in CommitteeLetter.objects.filter(pk__in=pending_reference_ids).order_by(
        "created_at",
        "id",
    ):
        year = letter.letter_date.year if letter.letter_date else django.utils.timezone.localdate().year
        next_number = max_by_year.get(year, 0) + 1
        max_by_year[year] = next_number
        letter.reference_number = f"THYG/COM/{year}/{next_number:03d}"
        letter.verification_code = _build_verification_code(
            letter.reference_number,
            used_codes,
        )
        letter.save(update_fields=["reference_number", "verification_code"])

    for year, last_number in max_by_year.items():
        LetterReferenceSequence.objects.update_or_create(
            year=year,
            defaults={"last_number": last_number},
        )


def upgrade_audit_logs(apps, schema_editor):
    CommitteeLetterAudit = apps.get_model("core", "CommitteeLetterAudit")

    action_map = {
        "created draft": "created",
        "letter created": "created",
        "edited draft": "edited",
        "letter edited": "edited",
        "submitted for review": "submitted",
        "submitted": "submitted",
        "returned for correction": "returned",
        "returned": "returned",
        "approved": "approved",
        "pdf generated": "pdf_generated",
        "issued": "issued",
        "cancelled": "cancelled",
        "correction draft created": "correction_created",
    }
    status_map = {
        "reviewed": "submitted",
        "pdf_generated": "approved",
    }

    for entry in CommitteeLetterAudit.objects.all():
        normalized_action = action_map.get((entry.action or "").strip().lower())
        if normalized_action:
            entry.action = normalized_action
        entry.status_from = status_map.get(entry.status_from, entry.status_from)
        entry.status_to = status_map.get(entry.status_to, entry.status_to)
        entry.save(update_fields=["action", "status_from", "status_to"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_lettertemplate_committeeletter_committeeletteraudit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterReferenceSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.RenameField(
            model_name="lettertemplate",
            old_name="body_template",
            new_name="default_body",
        ),
        migrations.AddField(
            model_name="lettertemplate",
            name="default_subject",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="lettertemplate",
            name="default_closing",
            field=models.CharField(blank=True, default="Yours faithfully,", max_length=120),
        ),
        migrations.AddField(
            model_name="lettertemplate",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="lettertemplate",
            name="footer_content",
        ),
        migrations.RemoveField(
            model_name="lettertemplate",
            name="header_content",
        ),
        migrations.AlterField(
            model_name="lettertemplate",
            name="letter_type",
            field=models.CharField(
                choices=[
                    ("general", "General committee letter"),
                    ("membership_confirmation", "Membership confirmation"),
                    ("loan_approval", "Loan approval"),
                    ("loan_repayment_reminder", "Loan repayment reminder"),
                    ("loan_demand", "Loan demand letter"),
                    ("welfare_communication", "Welfare communication"),
                    ("contribution_reminder", "Contribution reminder"),
                    ("appointment_letter", "Appointment letter"),
                    ("removal_notice", "Removal notice"),
                    ("partnership_letter", "Partnership letter"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="committeeletter",
            name="letter_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="committeeletter",
            name="recipient_position",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="committeeletter",
            name="salutation",
            field=models.CharField(default="Dear Sir/Madam,", max_length=120),
        ),
        migrations.AddField(
            model_name="committeeletter",
            name="closing_phrase",
            field=models.CharField(default="Yours faithfully,", max_length=120),
        ),
        migrations.AddField(
            model_name="committeeletter",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="committee_letters_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="committeeletter",
            name="review_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="committeeletter",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(upgrade_letters, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="committeeletter",
            name="date_issued",
        ),
        migrations.AlterField(
            model_name="committeeletter",
            name="letter_type",
            field=models.CharField(
                choices=[
                    ("general", "General committee letter"),
                    ("membership_confirmation", "Membership confirmation"),
                    ("loan_approval", "Loan approval"),
                    ("loan_repayment_reminder", "Loan repayment reminder"),
                    ("loan_demand", "Loan demand letter"),
                    ("welfare_communication", "Welfare communication"),
                    ("contribution_reminder", "Contribution reminder"),
                    ("appointment_letter", "Appointment letter"),
                    ("removal_notice", "Removal notice"),
                    ("partnership_letter", "Partnership letter"),
                ],
                default="general",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="committeeletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("returned", "Returned"),
                    ("approved", "Approved"),
                    ("issued", "Issued"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.RenameField(
            model_name="committeeletteraudit",
            old_name="note",
            new_name="comment",
        ),
        migrations.RunPython(upgrade_audit_logs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="committeeletteraudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Letter created"),
                    ("edited", "Letter edited"),
                    ("submitted", "Submitted"),
                    ("returned", "Returned"),
                    ("approved", "Approved"),
                    ("pdf_generated", "PDF generated"),
                    ("issued", "Issued"),
                    ("cancelled", "Cancelled"),
                    ("correction_created", "Correction draft created"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="committeeletteraudit",
            name="status_from",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("returned", "Returned"),
                    ("approved", "Approved"),
                    ("issued", "Issued"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="committeeletteraudit",
            name="status_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("returned", "Returned"),
                    ("approved", "Approved"),
                    ("issued", "Issued"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
