# Generated by Django 5.2.7 on 2026-08-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_committeeletter_schema_upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeletter',
            name='letter_type',
            field=models.CharField(choices=[('general', 'General committee letter'), ('membership_confirmation', 'Membership confirmation'), ('loan_approval', 'Loan approval'), ('loan_repayment_reminder', 'Loan repayment reminder'), ('loan_demand', 'Loan demand letter'), ('welfare_communication', 'Welfare communication'), ('contribution_reminder', 'Contribution reminder'), ('appointment_letter', 'Appointment letter'), ('removal_notice', 'Removal notice'), ('partnership_letter', 'Partnership letter'), ('disciplinary_committee', 'Disciplinary committee letter')], default='general', max_length=40),
        ),
        migrations.AlterField(
            model_name='committeeletter',
            name='recipient_address',
            field=models.TextField(blank=True, default='PO BOX 1109 ELDORET'),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='letter_type',
            field=models.CharField(choices=[('general', 'General committee letter'), ('membership_confirmation', 'Membership confirmation'), ('loan_approval', 'Loan approval'), ('loan_repayment_reminder', 'Loan repayment reminder'), ('loan_demand', 'Loan demand letter'), ('welfare_communication', 'Welfare communication'), ('contribution_reminder', 'Contribution reminder'), ('appointment_letter', 'Appointment letter'), ('removal_notice', 'Removal notice'), ('partnership_letter', 'Partnership letter'), ('disciplinary_committee', 'Disciplinary committee letter')], max_length=40),
        ),
    ]
