# Generated by Django 5.2.7 on 2026-08-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_committeeletter_letter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeletter',
            name='attention_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='committeeletter',
            name='attention_position',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='committeeletter',
            name='institution_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='committeeletter',
            name='institution_department',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='committeeletter',
            name='institution_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='committeeletter',
            name='institution_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='committeeletter',
            name='institution_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='committeeletter',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('government', 'Government'), ('parastatal', 'Parastatal'), ('ngo', 'NGO'), ('company', 'Company'), ('school', 'School'), ('church', 'Church'), ('bank', 'Bank'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='committeeletter',
            name='recipient_type',
            field=models.CharField(choices=[('member', 'Member'), ('institution', 'Institution / External')], default='member', max_length=20),
        ),
    ]
