# Generated by Codex on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_committeeletter_attention_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="announcement_date",
            field=models.DateField(
                blank=True,
                help_text="Optional date used to group homepage announcements.",
                null=True,
            ),
        ),
    ]
