# Generated by Django 5.2.7 on 2025-10-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('committee', 'Committee'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('coordinator', 'Coordinator'), ('welfare', 'Welfare'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
