# Generated by Django 5.2.7 on 2025-10-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chairperson', 'Chairperson'), ('committee', 'Committee'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('coordinator', 'Coordinator'), ('welfare', 'Welfare'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
