# Generated by Django 5.2.7 on 2025-10-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
