# Generated by Django 5.2.7 on 2025-11-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_membership_number_user_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chairperson', 'Chairperson'), ('vice-chairperson', 'Vice-Chairperson'), ('committee', 'Committee'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('vice-secretary', 'Vice-Secretary'), ('coordinator', 'Coordinator'), ('welfare', 'Welfare'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
